config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "to_do_lists#index"
  resources :to_do_lists do
    resources :to_do_items do
      member do
        patch :complete
        patch :uncomplete
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do_item.rb
class ToDoItem < ApplicationRecord
  belongs_to :to_do_list
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
  has_many :to_do_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController
  before_action :set_to_do_list
  before_action :set_to_do_item, except: :create

  def create
    if @to_do_item = @to_do_list.to_do_items.create(to_do_item_params)
      flash[:notice] = "Se agregó una tarea"
    else
      flash[:alert] = "No se pudo agregar la tarea"
    end
    redirect_to @to_do_list
  end

  def destroy
    @to_do_item = @to_do_list.to_do_items.find(params[:id])
    if @to_do_item.destroy
      flash[:notice] = "Se eliminó la tarea"
    else
      flash[:alert] = "No se pudo borrar la tarea"
    end
    redirect_to @to_do_list
  end

  def complete
    @to_do_item.update(completed: true)
    redirect_to @to_do_list, notice: "Tarea marcada como completada"
  end

  def uncomplete
    @to_do_item.update(completed: false)
    redirect_to @to_do_list, notice: "Tarea marcada como  incompleta"
  end

  private
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:to_do_list_id])
    end

    def set_to_do_item
      @to_do_item = @to_do_list.to_do_items.find(params[:id])
    end

    def to_do_item_params
      params[:to_do_item].permit(:title, :completed, :to_do_list_id)
    end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :set_to_do_list, only: %i[ show edit update destroy ]

  # GET /to_do_lists or /to_do_lists.json
  def index
    @to_do_lists = ToDoList.all
  end

  # GET /to_do_lists/1 or /to_do_lists/1.json
  def show
  end

  # GET /to_do_lists/new
  def new
    @to_do_list = ToDoList.new
  end

  # GET /to_do_lists/1/edit
  def edit
  end

  # POST /to_do_lists or /to_do_lists.json
  def create
    @to_do_list = ToDoList.new(to_do_list_params)

    respond_to do |format|
      if @to_do_list.save
        format.html { redirect_to @to_do_list, notice: "To do list was successfully created." }
        format.json { render :show, status: :created, location: @to_do_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_do_lists/1 or /to_do_lists/1.json
  def update
    respond_to do |format|
      if @to_do_list.update(to_do_list_params)
        format.html { redirect_to @to_do_list, notice: "To do list was successfully updated." }
        format.json { render :show, status: :ok, location: @to_do_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @to_do_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_lists/1 or /to_do_lists/1.json
  def destroy
    @to_do_list.destroy
    respond_to do |format|
      format.html { redirect_to to_do_lists_url, notice: "To do list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_do_list
      @to_do_list = ToDoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def to_do_list_params
      params.require(:to_do_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garagelabs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_do_items/_form.html.erb
<%= form_for([@to_do_list, @to_do_list.to_do_items.build]) do |form| %>
  <div class="field">
    <p>
      <%= form.label :title, "Tarea" %>
      <%= form.text_field :title %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= form.check_box :completed %>
      <%= form.label :completed, "Completada" %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/to_do_items/_to_do_item.html.erb
<tr class="to_do_item">
  <% if to_do_item.completed? %>
    <td>
      <%= link_to "Marcar como incompleta", uncomplete_to_do_list_to_do_item_path(@to_do_list, to_do_item.id), method: :patch %>
    </td>
    <td>
      <strike><span class="ready"> Ready </span></strike>
    </td>
    <td>
      <strike><span><%= to_do_item.title %></span></strike>
    </td>
  <% else %>
    <td>
      <%= link_to "Completar", complete_to_do_list_to_do_item_path(@to_do_list, to_do_item.id), method: :patch %>
    </td>
    <td>
      <span class="pendent"> Pendiente </span>
    </td>
    <td>
      <strong><%= to_do_item.title %></strong>
    </td>  
  <% end %>
  <td>
    <span><%= link_to "Eliminar tarea", to_do_list_to_do_item_path(@to_do_list, to_do_item.id), method: :delete, data: { confirm: "Confirmas que deseas eliminar esta tarea?" } %></span>
  </td>
</tr>

app/views/to_do_lists/_form.html.erb
<%= form_with(model: to_do_list, local: true) do |form| %>
  <% if to_do_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(to_do_list.errors.count, "error") %> prohibited this to_do_list from being saved:</h2>

      <ul>
        <% to_do_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/to_do_lists/edit.html.erb
<h1>Editing To Do List</h1>

<%= render 'form', to_do_list: @to_do_list %>

<%= link_to 'Show', @to_do_list %> |
<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Do Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_do_lists.each do |to_do_list| %>
      <tr>
        <td><%= to_do_list.title %></td>
        <td><%= to_do_list.description %></td>
        <td><%= link_to 'Show', to_do_list %></td>
        <td><%= link_to 'Edit', edit_to_do_list_path(to_do_list) %></td>
        <td><%= link_to 'Destroy', to_do_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To Do List', new_to_do_list_path %>

app/views/to_do_lists/new.html.erb
<h1>New To Do List</h1>

<%= render 'form', to_do_list: @to_do_list %>

<%= link_to 'Back', to_do_lists_path %>

app/views/to_do_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @to_do_list.title %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @to_do_list.description %>
</p>

<div id="to_do_items">
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Status</th>
        <th>Título de la tarea</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <%= render @to_do_list.to_do_items %>
  </table>
  <div id="form">
    <strong>Nueva tarea</strong>
    <%= render "to_do_items/form" %>
  </div>
</div>

<%= link_to 'Editar Lista', edit_to_do_list_path(@to_do_list) %> |
<%= link_to 'Todas las listas', to_do_lists_path %>